# Generated by Django 4.2.1 on 2023-06-09 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAsignatura', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClaseHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(max_length=200)),
                ('aula', models.CharField(max_length=200)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('diaSemana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asignatura')),
            ],
        ),
    ]
