# Generated by Django 4.2.1 on 2023-06-09 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuarioextendido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edificio', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='clasehorario',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'es_profesor': True}, on_delete=django.db.models.deletion.CASCADE, to='core.usuarioextendido'),
        ),
        migrations.AlterField(
            model_name='usuarioextendido',
            name='tipo_usuario',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Profesor'), (3, 'Alumno')], default=3),
        ),
        migrations.AlterField(
            model_name='clasehorario',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aula'),
        ),
    ]
